accounts/urls.py
from django.urls import path
from . import views
from .api_views import RegisterView, UserListCreateAPIView

app_name = 'accounts'

urlpatterns = [
    path('login/', views.user_login, name='user_login'),
    path('register/', views.user_register, name="user_register"),
    path('logout/', views.user_logout, name="user_logout"),
    path('register-view/', RegisterView.as_view()),
    path('login-view/', UserListCreateAPIView.as_view()),
    path('confirm-register/', views.confirm_registration, name='confirm'),
]

store/urls.py
from django.urls import path
from . import views
from .api_views import CategoryListApiView, CategoryDetailApiView, ProductDetailApiView, ProductListApiView

app_name = 'store'
urlpatterns = [

    path('product-detail/<int:id>/', views.product_detail, name='product-detail'),
    path('category-list/', views.category_list, name='category-list'),
    path('category_product_list/<int:cat_id>/', views.category_product_list, name='category-product-list'),


    path('api/category-list/', CategoryListApiView.as_view(), name='category_list'),
    path('api/category-detail/<int:pk>/', CategoryDetailApiView.as_view(), name='category_detail'),
    path('api/product-detail/<int:pk>/', ProductDetailApiView.as_view(), name='product_detail'),
    path('api/product-list/', ProductListApiView.as_view(), name='product_list'),

]

yara/urls.py
from django.contrib import admin
from django.urls import path, include
# from.api_urls import router
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token)

]

templates/inc/messages.html
{% if messages %}
     {% for message in messages %}
        <p class="alert alert-{{ message.tags }}"> {{ message }}</p>
     {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="navbar-nav">
            <a class="navbar-brand" href="{% url 'store:category-list' %}">Navbar</a>

            {% if request.user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">logout</a>


            {% else %}
            <a class="navbar-brand" href="{% url 'accounts:user_login' %}">login</a>
            <a class="navbar-brand" href="{% url 'accounts:user_register' %}">register</a>
            {% endif %}


        </div>
</nav>