crawler/urls.py
from django.urls import path
from . import views

app_name = 'crawler'
urlpatterns = [

    path('product-detail/<int:id>/', views.product_detail, name='product-detail'),
    path('category-list/', views.category_list, name='category-list'),
    path('category_product_list/<int:cat_id>/', views.category_product_list, name='category-product-list'),

]

yara/urls.py
from django.contrib import admin
from django.urls import path, include
# from.api_urls import router
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token)

]

crawler/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    title = models.CharField(verbose_name=_("title"), max_length=350)
    created_at = models.DateTimeField(verbose_name=_('created time'), auto_now_add=True)
    updated_time = models.DateTimeField(verbose_name=_("updated time"), auto_now=True)
    is_enabled = models.BooleanField(verbose_name=_("is_enabled"), default=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'category'
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Product(models.Model):
    name = models.CharField(verbose_name=_("name"), max_length=130, blank=True)
    price = models.CharField(verbose_name=_("price"), max_length=50, blank=True)
    category = models.ForeignKey(Category, verbose_name=_('category'), on_delete=models.CASCADE, related_name='products')
    created_time = models.DateTimeField(verbose_name=_('Created time'), auto_now_add=True)
    updated_time = models.DateTimeField(verbose_name=_('updated time'), auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'product'
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

crawler/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


def category_product_list(request, cat_id):
    category = Category.objects.get(id=cat_id)
    data = Product.objects.filter(category=category)
    return render(request, 'crawler/category_product_list.html', {'data':data})

def category_list(request):
    categories = Category.objects.all()
    return render(request, 'crawler/category_list.html', {'categories':categories})



def product_detail(request, id):
    product = Product.objects.get(id=id)
    context = {'product': product}
    return render(request, 'crawler/product_detail.html', context)

crawler/templates/crawler/category_list.html
{% extends 'base.html' %}
{% block content %}
{% for category in categories %}
<a href="{%url 'crawler:category-product-list' category.id %}">{{category.title}}</a>
<p></p>


{% endfor %}
{% endblock %}

crawler/templates/crawler/category_product_list.html
{% extends 'base.html' %}
{% block content %}
{% for product in data %}
<a href="{% url 'crawler:product-detail' product.id %}"> {{product.name}}<br> </a><br>
{% endfor %}
{% endblock %}

crawler/templates/crawler/product_list.html
{% extends 'base.html' %}
{% block content %}
{% for product in products%}


<a href="{% url 'crawler:product-detail' product.id %}"> {{product.name}} </a><hr>

{% endfor %}
{% endblock %}